version: '3'
services:
  streamlit-app:
    build: .
    image: bank-simul-streamlit-app  # 修改这一行
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_BASE_URL_PATH=/bank-simul

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - streamlit-app